import type { Metadata } from "next";
import { Breadcrumb } from "@/components/seo/Breadcrumb";
import { FAQ } from "@/components/seo/FAQ";
import { Schema, faqSchema } from "@/components/seo/Schema";
import { rentingFaqs } from "@/data/renting-faqs";

export const metadata:Metadata={title:"Preguntas frecuentes sobre renting",description:"Respuestas claras sobre cuotas, IVA, kilometraje, seguro, mantenimiento, documentación, fiscalidad y finalización del renting.",alternates:{canonical:"/preguntas-frecuentes"}};
export default function FrequentlyAskedQuestionsPage(){const groups=[...new Set(rentingFaqs.map(item=>item.group))];return <main id="contenido-principal" className="mx-auto max-w-5xl px-5 py-7 sm:px-8 sm:py-10"><Breadcrumb items={[{name:"Inicio",path:"/"},{name:"Preguntas frecuentes",path:"/preguntas-frecuentes"}]}/><Schema data={faqSchema(rentingFaqs)}/><p className="text-xs font-bold tracking-[0.1em] text-brand uppercase">Centro de respuestas</p><h1 className="font-display mt-3 text-4xl font-semibold tracking-[-0.05em] text-ink sm:text-6xl">Preguntas frecuentes sobre renting</h1><p className="mt-5 max-w-3xl text-base leading-7 text-muted">Respuestas revisadas para entender una oferta antes de contratar. Las condiciones del contrato del proveedor siempre prevalecen.</p><nav aria-label="Temas" className="mt-8 flex flex-wrap gap-2">{groups.map(group=><a key={group} href={`#${slug(group)}`} className="rounded-full border border-line bg-surface px-3 py-2 text-xs font-bold text-copy hover:border-brand">{group}</a>)}</nav><div className="mt-12 space-y-12">{groups.map(group=><section key={group} id={slug(group)} className="scroll-mt-24"><div className="grid gap-5 border-t border-line pt-7 md:grid-cols-[13rem_1fr]"><h2 className="font-display text-2xl font-semibold tracking-[-0.03em] text-ink">{group}</h2><FAQ items={rentingFaqs.filter(item=>item.group===group)}/></div></section>)}</div></main>}
function slug(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
