import type { Metadata } from "next";
import Link from "next/link";
import { Breadcrumb } from "@/components/seo/Breadcrumb";
import { PublicReviews } from "@/components/reviews/PublicReviews";
import { Schema } from "@/components/seo/Schema";
import { absoluteUrl } from "@/lib/seo";

export const metadata:Metadata={title:"Opiniones verificadas de clientes",description:"Experiencias reales de clientes de MyRenting, publicadas con consentimiento y sin incentivos.",alternates:{canonical:"/opiniones"},openGraph:{type:"website",title:"Opiniones verificadas de clientes",description:"Experiencias enviadas mediante invitación individual, moderadas con el mismo criterio para valoraciones positivas y negativas.",url:"/opiniones"}};

export default function ReviewsPage(){return <main className="mx-auto max-w-6xl px-5 py-8 sm:px-8 sm:py-12"><Schema data={{"@context":"https://schema.org","@type":"CollectionPage","@id":`${absoluteUrl("/opiniones")}#webpage`,url:absoluteUrl("/opiniones"),name:"Opiniones verificadas de clientes",description:"Experiencias enviadas mediante invitación individual y publicadas con consentimiento.",isPartOf:{"@id":`${absoluteUrl("/")}#website`},publisher:{"@id":`${absoluteUrl("/")}#organization`},inLanguage:"es-ES"}}/><Breadcrumb items={[{name:"Inicio",path:"/"},{name:"Opiniones",path:"/opiniones"}]}/><header className="border-b border-line pb-10"><p className="text-xs font-bold tracking-[0.1em] text-brand uppercase">Experiencias reales</p><h1 className="font-display mt-3 text-4xl font-semibold tracking-[-0.05em] text-ink sm:text-6xl">Opiniones verificadas</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted">Solo publicamos opiniones enviadas mediante una invitación vinculada a un cliente. No pagamos por reseñas y las críticas se moderan con el mismo criterio que las positivas.</p></header><PublicReviews/><section className="mt-12 rounded-xl border border-line bg-surface p-7"><h2 className="font-display text-2xl font-semibold">Cómo verificamos una opinión</h2><ol className="mt-5 grid gap-4 text-sm leading-6 text-copy sm:grid-cols-3"><li><strong className="block text-ink">1. Invitación única</strong>El enlace se genera para un cliente y solo puede utilizarse una vez.</li><li><strong className="block text-ink">2. Consentimiento</strong>La persona autoriza expresamente la publicación de los datos visibles.</li><li><strong className="block text-ink">3. Moderación neutral</strong>Solo retiramos datos personales, spam o contenido ilícito, sin alterar el sentido.</li></ol><Link href="/politica-editorial" className="mt-5 inline-block text-sm font-bold text-brand">Leer la política completa →</Link></section><section className="mt-12 rounded-xl bg-ink p-7 text-white"><h2 className="font-display text-2xl font-semibold">Nuestro criterio de publicación</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Verificamos la invitación, eliminamos datos personales y spam, y respetamos el sentido de cada experiencia. Puedes solicitar la rectificación o retirada escribiendo a mtiagconsulting@gmail.com.</p><Link href="/politica-editorial" className="mt-5 inline-block text-sm font-bold text-orange-400">Consultar la metodología →</Link></section></main>}

